// Generates THIRD_PARTY_NOTICES.md: production npm dependencies (with their
// licenses read from node_modules) plus the bundled binaries and models.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))

const seen = new Map()
function walk(name) {
  if (seen.has(name)) return
  const dir = path.join(root, 'node_modules', name)
  const pj = path.join(dir, 'package.json')
  if (!existsSync(pj)) return
  const meta = JSON.parse(readFileSync(pj, 'utf8'))
  let licenseText = null
  for (const f of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'license']) {
    const p = path.join(dir, f)
    if (existsSync(p)) {
      licenseText = readFileSync(p, 'utf8').slice(0, 400)
      break
    }
  }
  seen.set(name, {
    version: meta.version,
    license: meta.license ?? 'see repository',
    homepage: meta.homepage ?? meta.repository?.url ?? '',
  })
  for (const dep of Object.keys(meta.dependencies ?? {})) walk(dep)
}
for (const dep of Object.keys(pkg.dependencies ?? {})) walk(dep)

const BUNDLED = [
  ['ffmpeg (gyan.dev full build)', 'GPL-2.0-or-later (includes libx264, x265)', 'https://ffmpeg.org — source: https://github.com/GyanD/codexffmpeg'],
  ['whisper.cpp (whisper-cli)', 'MIT', 'https://github.com/ggml-org/whisper.cpp'],
  ['llama.cpp (llama-server)', 'MIT', 'https://github.com/ggml-org/llama.cpp'],
  ['Electron', 'MIT', 'https://electronjs.org'],
  ['Chromium (within Electron)', 'BSD-3-Clause and others', 'https://chromium.org'],
  ['Node.js (within Electron)', 'MIT', 'https://nodejs.org'],
]

const MODELS = [
  ['Whisper large-v3-turbo (OpenAI)', 'MIT', 'https://github.com/openai/whisper'],
  ['Silero VAD', 'MIT', 'https://github.com/snakers4/silero-vad'],
  ['pyannote segmentation 3.0', 'MIT', 'https://huggingface.co/pyannote/segmentation-3.0'],
  ['3D-Speaker ERes2Net', 'Apache-2.0', 'https://github.com/modelscope/3D-Speaker'],
  ['SmolVLM2-2.2B-Instruct (HuggingFace)', 'Apache-2.0', 'https://huggingface.co/HuggingFaceTB/SmolVLM2-2.2B-Instruct'],
  ['Qwen3-4B-Instruct-2507 (Alibaba)', 'Apache-2.0', 'https://huggingface.co/Qwen/Qwen3-4B-Instruct-2507'],
  ['Tesseract eng.traineddata', 'Apache-2.0', 'https://github.com/tesseract-ocr/tessdata_fast'],
]

const lines = [
  '# Third-Party Notices',
  '',
  'MeetFroge is licensed under GPL-3.0-or-later and stands on the following work.',
  `Generated by scripts/gen-notices.mjs on ${new Date().toISOString().slice(0, 10)}.`,
  '',
  '## Bundled binaries',
  '',
  '| Component | License | Source |',
  '|---|---|---|',
  ...BUNDLED.map(([n, l, u]) => `| ${n} | ${l} | ${u} |`),
  '',
  'The bundled ffmpeg build is GPL because it includes libx264/x265 — the reason',
  'MeetFroge itself is GPL-3.0 (see DECISIONS.md ADR-009). Corresponding sources are',
  'available at the URLs above.',
  '',
  '## Machine-learning models (downloaded on demand, not distributed in the installer)',
  '',
  '| Model | License | Source |',
  '|---|---|---|',
  ...MODELS.map(([n, l, u]) => `| ${n} | ${l} | ${u} |`),
  '',
  '## npm dependencies (production)',
  '',
  '| Package | Version | License |',
  '|---|---|---|',
  ...[...seen.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, m]) => `| ${name} | ${m.version} | ${m.license} |`),
  '',
]
writeFileSync(path.join(root, 'THIRD_PARTY_NOTICES.md'), lines.join('\n'))
console.log(`THIRD_PARTY_NOTICES.md written: ${seen.size} npm packages + ${BUNDLED.length} binaries + ${MODELS.length} models`)
